CORE_SOURCE_FILES 			= $(SOURCE_FILES)
CORE_OBJECT_FILES 			= $(patsubst %.cpp,$(BUILD_DIRECTORY)/%.o, $(CORE_SOURCE_FILES))
CORE_DEPENDENCY_FILES 	= $(patsubst %.cpp,$(BUILD_DIRECTORY)/%.d, $(CORE_SOURCE_FILES))
CORE_LIBRARIES					=
CORE_LIBRARY 				= $(BINARY_DIRECTORY)/core.lib

core: 		CPP_INCLUDES += -Iinclude
core: 		$(CORE_LIBRARY)

$(CORE_LIBRARY):	$(CORE_OBJECT_FILES) $(CORE_LIBRARIES)
	@$(MKDIR) $(@D)
	$(REMOVE) $(CORE_LIBRARY)
	$(ARCHIVE) $@ $^

core-clean:
	$(REMOVE) $(CORE_LIBRARY) $(CORE_OBJECT_FILES) $(CORE_DEPENDENCY_FILES)
	
.PHONY: core-clean

-include $(CORE_DEPENDENCY_FILES)